### ISSUE TITLE
Maven build failure

### ISSUE THREAD

**Issue by calvinmclean** [mike-jumper/guacamole-auth-openid#1]
Hi,

I am having troubles using this extension. 

When I try and build with `sudo mvn package` I get this output: [openid-build-output.txt](https://github.com/mike-jumper/guacamole-auth-openid/files/413854/openid-build-output.txt)

I noticed that the version specified was `0.9.9-Incubating` so I changed all occurrences of `0.9.9-Incubating` to just `0.9.9`.

Then, `sudo mvn package -U`  gives the output: [openid-build-output2.txt](https://github.com/mike-jumper/guacamole-auth-openid/files/413858/openid-build-output2.txt) where it looks like the only difference is it no longer says `0.9.9-Incubating`

So I follow the instructions to install the dependencies manually with jars found at:
http://central.maven.org/maven2/org/glyptodon/guacamole/guacamole-ext/0.9.9/ and
http://central.maven.org/maven2/org/glyptodon/guacamole/guacamole-common/0.9.9/

and I still get errors: [openid-build-output3.txt](https://github.com/mike-jumper/guacamole-auth-openid/files/413880/openid-build-output3.txt)

Any assistance is appreciated, thanks!!

**Comment by mike-jumper** [comment]
> When I try and build with `sudo mvn package` I get this output: [openid-build-output.txt](https://github.com/mike-jumper/guacamole-auth-openid/files/413854/openid-build-output.txt)

This is because 0.9.9-incubating doesn't really exist - it's the version number for the current state of git since the project's acceptance into the Apache Incubator. It does not exist in Maven Central.

To build anything against 0.9.9-incubating, you will need to run `mvn install` within a cloned copy of [incubator-guacamole-client](https://github.com/apache/incubator-guacamole-client).

> I noticed that the version specified was `0.9.9-Incubating` so I changed all occurrences of `0.9.9-Incubating` to just `0.9.9`.

This is never a safe thing to do. The versions are different because they are actually different.

> Then, `sudo mvn package -U`  gives the output: [openid-build-output2.txt](https://github.com/mike-jumper/guacamole-auth-openid/files/413858/openid-build-output2.txt) where it looks like the only difference is it no longer says `0.9.9-Incubating`

This is because there is no version 0.9.9 under the `org.apache.guacamole` group ID. That release occurred before acceptance into the Apache Incubator, and thus the group ID was `org.glyptodon.guacamole`. You _still_ can't build this against that, however. 0.9.9 and 0.9.9-incubating are not interchangeable.

> So I follow the instructions to install the dependencies manually with jars found at:
> http://central.maven.org/maven2/org/glyptodon/guacamole/guacamole-ext/0.9.9/ and
> http://central.maven.org/maven2/org/glyptodon/guacamole/guacamole-common/0.9.9/
> 
> and I still get errors: [openid-build-output3.txt](https://github.com/mike-jumper/guacamole-auth-openid/files/413880/openid-build-output3.txt)

The errors you are now getting are due to 0.9.9 being completely different from 0.9.9-incubating. They do not contain the same classes, and they are very much not compatible.

If you do a `mvn install` for the upstream incubator-guacamole-client repository, that should allow the build to succeed here, though you will need to revert everything you've changed so far.
